/* Passlink offline shell — generated by build-pwa.py. Do not edit by hand.

   BUILD is the content hash of the page. It is the only reason this file
   changes when the page changes, which is what lets a fix reach someone who
   already installed the app: Chrome byte-compares this script and skips
   install entirely if it is identical. */
const BUILD = 'f325a28cc252';
const CACHE = 'passlink-' + BUILD;
/* Stamped from the filename actually built, not guessed. Getting it wrong makes
   install reject and offline silently never work at all. */
const SHELL = './index.dev.html';

/* cache: 'reload' so the shell comes from the network rather than out of the
   HTTP cache — otherwise a fresh install can enshrine a stale page. */
self.addEventListener('install', e => e.waitUntil(
  caches.open(CACHE)
    .then(c => c.add(new Request(SHELL, {cache: 'reload'})))
    .then(() => self.skipWaiting())));

self.addEventListener('activate', e => e.waitUntil(
  caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim())));

/* Cache-first, since the whole point is to work with no network at all. The URL
   fragment is never sent in a request, so it never arrives here — which is why
   this single cached copy answers every #blob link. */
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  if (e.request.mode === 'navigate'){
    e.respondWith(caches.match(SHELL).then(r => r || fetch(e.request)));
    return;
  }
  e.respondWith(caches.match(e.request).then(r => r || fetch(e.request)));
});

/* No 'message' listener, deliberately. Nothing needs one, and it is the single
   thing that would let an injected script reach the network: the page's
   connect-src 'none' does not apply to a worker, and a worker on static
   hosting cannot be given a policy of its own. Measured both ways — with a
   handler the secret left the machine, without one there is no channel. */
